  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'CEO','1');
  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'Administration','1-1');
  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'Legal','1-1-1');
  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'Archives','1-1-2');
  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'Production','1-2');
  INSERT INTO UNIT VALUES(NEXT VALUE FOR seq1,'Sales','2');